# Generated by Django 4.2.4 on 2023-08-17 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bliblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ingrese el nombre de la biblioteca.', max_length=50)),
                ('direction', models.CharField(help_text='ingrese la direccion de la biblioteca', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ingrese el nombre del libro', max_length=100)),
                ('isbn', models.CharField(help_text='ingrese el isbn del libro', max_length=100)),
                ('autor', models.CharField(help_text='ingrese el autor del libro', max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bliblioteca')),
            ],
        ),
    ]
