# Generated by Django 4.2.4 on 2023-08-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_libro_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bliblioteca',
            name='direction',
            field=models.CharField(help_text='ingrese la direccion de la biblioteca', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(help_text='ingrese el autor del libro', max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='done',
            field=models.CharField(help_text='ingrese si el libro esta prestado o en sala', max_length=8),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(help_text='ingrese el ISBN del libro', max_length=13),
        ),
        migrations.AlterField(
            model_name='libro',
            name='name',
            field=models.CharField(help_text='ingrese el nombre del libro', max_length=50),
        ),
    ]
